### In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

Answer : 53713.86 and 93747.79

In [4]:
pip install word2number


  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5595 sha256=b52ee6cbee3ab2e7371826f22af8de3a995467e98084ef5a44aeb21edab268b0
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number


In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n # as linear regression works only on numbers so we need to change the words to numbers.

In [36]:
df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [37]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [38]:
df.experience = df.experience.apply(w2n.word_to_num)

In [39]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [43]:
df_median = df["test_score(out of 10)"].median()
df_median

8.0

In [44]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(df_median)

In [45]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [47]:
reg = linear_model.LinearRegression()
reg.fit(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],df["salary($)"])

LinearRegression()

In [48]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [49]:
reg.intercept_

17737.26346433771

In [51]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [54]:
reg.predict([[12,10,10]])

array([92002.18340611])